### ISSUE TITLE
Error getting corpus iterator

### ISSUE THREAD

**Issue by AmenRa** [terrierteam/pyterrier_adaptive#1]
Hi, I am trying to build the graph (just the graph) following the readme example, but I get this error:

```python
Traceback (most recent call last):
  File "/mnt/MX500/corpus_graph/build_graph.py", line 31, in <module>
    main()
  File "/mnt/MX500/corpus_graph/build_graph.py", line 13, in main
    idx.index(dataset.get_corpus_iter())
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elias/miniconda3/envs/pyterrier/lib/python3.11/site-packages/pyterrier/datasets.py", line 414, in get_corpus_iter
    it = tqdm(it, desc=f'{self._irds_id} documents', total=total)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

What should I do?

Thanks,

Elias

**Comment by seanmacavaney** [comment]
Hi Elias!

Thanks for reporting. You’ll need to import pyterrier and run pt.init() before importing pyterrier_adaptive.

We’ve got plans to move more features out of pt.init() to avoid these sorts of issues, put haven’t done pt.tqdm yet.

 - sean

**Comment by AmenRa** [comment]
Ok, thanks!

Best,

Elias

**Comment by cmacdonald** [comment]
> We’ve got plans to move more features out of pt.init() to avoid these sorts of issues, put haven’t done pt.tqdm yet.

And this one is an easy fix :-)

**Comment by cmacdonald** [comment]
and the fix is done, will be in next PyTerrier release.
